# Generated by Django 4.2.7 on 2023-12-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammanager', '0002_member_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('regular', 'Regular')], default='Regular', max_length=8),
        ),
    ]
